### ISSUE TITLE
Using the Command

### ISSUE THREAD

**Issue by Yumshot** [Krizfrost/CivLife-UberDelivery#1]
Using the command to enable uber , doing 1 delivery then toggling the delivery , will still give you another delivery even once offduty

**Comment by MrMallenby** [comment]
Can confirm same issue

**Comment by ghost** [comment]
Yeah it doesn't actually stop the delivery when you disable it for whatever reason

**Comment by KrizKhaoz** [comment]
It only provides them with 1 delivery at the end after you end the uber.  this is due to the wait period between deliveries, will more then likely push a fix shortly.

**Comment by ghost** [comment]
Any update?
